# Spring Boot configuration
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: letoxytv@gmail.com
    password: cugvelcbeuehxvsw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        ssl:
          enable: false
    test-connection: true
    verify:
      host: http://localhost:8080

  flyway:
    baseline-on-migrate: true
  profiles:
    active:
  # Security configuration
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/store
    username: joel
    password: joel
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080 #set your port
